modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="allaboutengie"
version="9.6.25"
displayName="RE:All About Engie"
updateJSONURL="https://raw.githubusercontent.com/EngieGames/All-About-Engie/refs/heads/master/ModUpdateCheck.json"
displayURL="https://modrinth.com/project/re-all-about-engie"
logoFile="logo.png"
credits="DevEngie (Original Mod Creator)"
authors="EngieGames"
description="A collection of all my other mods for my 5th year of making mods! If you find issues, report them on the GitHub page for the mod please."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.allaboutengie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration